=== javiersu01/LenguajeDeMarcas/dtd.dtd
<!ELEMENT pedidos (pedido*)>     
    <!ELEMENT pedido (numero, nombre, apellido, telefono, direccion, email, fecha_inclusion,datosPedido)>
        <!ELEMENT numero (#PCDATA)>    
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT apellido (#PCDATA)>
        <!ELEMENT telefono (#PCDATA)>
    <!ELEMENT direccion (calle, ciudad, codigo_postal, provincia)>
        <!ELEMENT calle (#PCDATA)>
        <!ELEMENT ciudad (#PCDATA)>
        <!ELEMENT codigo_postal (#PCDATA)>
        <!ELEMENT provincia (#PCDATA)>
        <!ELEMENT email (#PCDATA)>
    <!ELEMENT fecha_inclusion (fecha,año,trimestre)>
        <!ELEMENT fecha (#PCDATA)>
        <!ELEMENT año (#PCDATA)>
        <!ELEMENT trimestre (#PCDATA)>
    <!ELEMENT datosPedido (id_pedido, fecha_compra, fecha_entrega, total_factura, producto)>
        <!ELEMENT id_pedido (#PCDATA)>
        <!ELEMENT fecha_compra (#PCDATA)>
        <!ELEMENT fecha_entrega (#PCDATA)>
        <!ELEMENT total_factura (#PCDATA)>
    <!ELEMENT producto (nombre_producto, referencia, precio, unidades)>
        <!ELEMENT nombre_producto (#PCDATA)>
        <!ELEMENT referencia (#PCDATA)>
        <!ELEMENT precio (#PCDATA)>
        <!ELEMENT unidades (#PCDATA)>

=== javiersu01/LenguajeDeMarcas/fase1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedidos SYSTEM "./dtd.dtd">
<pedidos>

   
    <pedido>
        <numero>01</numero>
        <nombre>Wanda</nombre>
        <apellido>Wolters</apellido>
        <telefono>611-222-333</telefono>
        <direccion>
            <calle>Calle mayor</calle>
            <ciudad>Colorado</ciudad>
            <codigo_postal>28017</codigo_postal>
            <provincia></provincia>
        </direccion>
        <email>j.Wolters@gmail.com</email>
        <fecha_inclusion>
            <fecha>01/01/2022</fecha>
            <año>2022</año>
            <trimestre>1</trimestre>
        </fecha_inclusion>
        <datosPedido>
            <id_pedido>01</id_pedido>
            <fecha_compra>10/01/2021</fecha_compra>
            <fecha_entrega>15/01/2021</fecha_entrega>
            <total_factura>20€</total_factura>
            <producto>
                <nombre_producto>Cookie Dough</nombre_producto>
                <referencia>01</referencia>
                <precio>20€</precio>
                <unidades>1</unidades>
            </producto>
        </datosPedido>
    </pedido>

    <pedido>
        <numero>02</numero>
        <nombre>Ryann</nombre>
        <apellido>Reasce</apellido>
        <telefono>644-555-666</telefono>
        <direccion>
            <calle>Calle ferrocarril</calle>
            <ciudad>Getafe</ciudad>
            <codigo_postal>28907</codigo_postal>
            <provincia>Madrid</provincia>
        </direccion>
        <email>j.Reasce@gmail.com</email>
        <fecha_inclusion>
            <fecha>02/01/2021</fecha>
            <año>2021</año>
            <trimestre>1</trimestre>
        </fecha_inclusion>
        <datosPedido>
            <id_pedido>02</id_pedido>
            <fecha_compra>02/01/2021</fecha_compra>
            <fecha_entrega>09/01/2021</fecha_entrega>
            <total_factura>20€</total_factura>
            <producto>
                <nombre_producto>Peanut Butter</nombre_producto>
                <referencia>02</referencia>
                <precio>30€</precio>
                <unidades>1</unidades>
            </producto>
        </datosPedido>
    </pedido>

    <pedido>
        <numero>03</numero>
        <nombre>Claudetta</nombre>
        <apellido>Jewise</apellido>
        <telefono>647-898-766</telefono>
        <direccion>
            <calle>Calle Kinsman</calle>
            <ciudad>Toledo</ciudad>
            <codigo_postal>28908</codigo_postal>
            <provincia>Toledo</provincia>
        </direccion>
        <email>danieda.db@gmail.com</email>
        <fecha_inclusion>
            <fecha>15/03/2021</fecha>
            <año>2021</año>
            <trimestre>1</trimestre>
        </fecha_inclusion>
        <datosPedido>
            <id_pedido>03</id_pedido>
            <fecha_compra>15/03/2021</fecha_compra>
            <fecha_entrega>20/03/2021</fecha_entrega>
            <total_factura>22€</total_factura>
            <producto>
                <nombre_producto>Muffin Chocolate</nombre_producto>
                <referencia>03</referencia>
                <precio>25€</precio>
                <unidades>1</unidades>
            </producto>
        </datosPedido>
    </pedido>

    <pedido>
        <numero>04</numero>
        <nombre>Ninette</nombre>
        <apellido>Bresner</apellido>
        <telefono>688-926-774</telefono>
        <direccion>
            <calle>Calle Delladonna</calle>
            <ciudad>Getafe</ciudad>
            <codigo_postal>28903</codigo_postal>
            <provincia>Madrid</provincia>
        </direccion>
        <email>paulaBresner@gmail.com</email>
        <fecha_inclusion>
            <fecha>10/03/2021</fecha>
            <año>2021</año>
            <trimestre>1</trimestre>
        </fecha_inclusion>
        <datosPedido>
            <id_pedido>03</id_pedido>
            <fecha_compra>10/03/2021</fecha_compra>
            <fecha_entrega>16/03/2021</fecha_entrega>
            <total_factura>24€</total_factura>
            <producto>
                <nombre_producto>Potatoes</nombre_producto>
                <referencia>04</referencia>
                <precio>24€</precio>
                <unidades>1</unidades>
            </producto>
        </datosPedido>
    </pedido>

    <pedido>
        <numero>05</numero>
        <nombre>Kathe</nombre>
        <apellido>Thrush</apellido>
        <telefono>693-367-645</telefono>
        <direccion>
            <calle>Calle Grishagin</calle>
            <ciudad>Barcelona</ciudad>
            <codigo_postal>28903</codigo_postal>
            <provincia>Barcelona</provincia>
        </direccion>
        <email>j.Thrush@gmail.com</email>
        <fecha_inclusion>
            <fecha>27/01/2021</fecha>
            <año>2021</año>
            <trimestre>1</trimestre>
        </fecha_inclusion>
        <datosPedido>
            <id_pedido>05</id_pedido>
            <fecha_compra>27/01/2021</fecha_compra>
            <fecha_entrega>02/02/2021</fecha_entrega>
            <total_factura>35€</total_factura>
            <producto>
                <nombre_producto>Spring Water</nombre_producto>
                <referencia>05</referencia>
                <precio>35€</precio>
                <unidades>1</unidades>
            </producto>
        </datosPedido>
    </pedido>

    <pedido>
        <numero>06</numero>
        <nombre>Loreen</nombre>
        <apellido>Talby</apellido>
        <telefono>863-690-6102</telefono>
        <direccion>
            <calle>Springview</calle>
            <ciudad>Lehigh Acres</ciudad>
            <codigo_postal>33972</codigo_postal>
            <provincia>Florida</provincia>
        </direccion>
        <email>anto@yahoo.com</email>
        <fecha_inclusion>
            <fecha>10/04/2021</fecha>
            <año>2021</año>
            <trimestre>1</trimestre>
        </fecha_inclusion>
        <datosPedido>
            <id_pedido>06</id_pedido>
            <fecha_compra>10/04/2021</fecha_compra>
            <fecha_entrega>12/04/2021</fecha_entrega>
            <total_factura>85,25 €</total_factura>
            <producto>
                <nombre_producto> Vodka Blush</nombre_producto>
                <referencia>06</referencia>
                <precio>17,05 €</precio>
                <unidades>5</unidades>
            </producto>
        </datosPedido>
    </pedido>

    <pedido>
        <numero>07</numero>
        <nombre>Benedikt</nombre>
        <apellido>Britto</apellido>
        <telefono>765-731-6660</telefono>
        <direccion>
            <calle>Fallview</calle>
            <ciudad>Crawfordsville</ciudad>
            <codigo_postal>47937</codigo_postal>
            <provincia>Indiana</provincia>
        </direccion>
        <email>holar6@mit.edu</email>
        <fecha_inclusion>
            <fecha>13/03/2021</fecha>
            <año>2021</año>
            <trimestre>1</trimestre>
        </fecha_inclusion>
        <datosPedido>
            <id_pedido>07</id_pedido>
            <fecha_compra>13/03/2021</fecha_compra>
            <fecha_entrega>20/03/2021</fecha_entrega>
            <total_factura>9,83 €</total_factura>
            <producto>
                <nombre_producto>Salmon Steak</nombre_producto>
                <referencia>07</referencia>
                <precio>9,83 €</precio>
                <unidades>1</unidades>
            </producto>
        </datosPedido>
    </pedido>

    <pedido>
        <numero>08</numero>
        <nombre>Lew</nombre>
        <apellido>suarez</apellido>
        <telefono>713-560-5203</telefono>
        <direccion>
            <calle>Roth</calle>
            <ciudad>Houston</ciudad>
            <codigo_postal>77228</codigo_postal>
            <provincia>Texas</provincia>
        </direccion>
        <email>suarez7@domainmarket.com</email>
        <fecha_inclusion>
            <fecha>23/02/2021</fecha>
            <año>2021</año>
            <trimestre>1</trimestre>
        </fecha_inclusion>
        <datosPedido>
            <id_pedido>08</id_pedido>
            <fecha_compra>23/02/2021</fecha_compra>
            <fecha_entrega>28/02/2021</fecha_entrega>
            <total_factura>8 €</total_factura>
            <producto>
                <nombre_producto>Wanton Wrap</nombre_producto>
                <referencia>07</referencia>
                <precio>4 €</precio>
                <unidades>2</unidades>
            </producto>
        </datosPedido>
    </pedido>

    <pedido>
        <numero>09</numero>
        <nombre>Ardyth</nombre>
        <apellido>McClintock</apellido>
        <telefono>619-440-9406</telefono>
        <direccion>
            <calle>West</calle>
            <ciudad>Getafe</ciudad>
            <codigo_postal>28905</codigo_postal>
            <provincia>Madrid</provincia>
        </direccion>
        <email>buenas@mh.com</email>
        <fecha_inclusion>
            <fecha>25/03/2021</fecha>
            <año>2021</año>
            <trimestre>1</trimestre>
        </fecha_inclusion>
        <datosPedido>
            <id_pedido>09</id_pedido>
            <fecha_compra>25/03/2021</fecha_compra>
            <fecha_entrega>30/03/2021</fecha_entrega>
            <total_factura>30 €</total_factura>
            <producto>
                <nombre_producto>Icecream </nombre_producto>
                <referencia>09</referencia>
                <precio>30 €</precio>
                <unidades>1</unidades>
            </producto>
        </datosPedido>
    </pedido>

    <pedido>
        <numero>10</numero>
        <nombre>Jodi</nombre>
        <apellido>Reade</apellido>
        <telefono>865-500-0330</telefono>
        <direccion>
            <calle>Steensland</calle>
            <ciudad>Rutledge</ciudad>
